Carlos
CampusDual/ProyectoGAG3 pull request #5
Opened 2020-06-12 09:33 UTC by carlosgonzalez-campusdual

Creados servicios, controladores, dao de reparto y generos. A develop

2020-06-12 12:16 UTC, icossinib requested changes

2020-06-12 12:16 UTC, icossinib commented on frontend/pom.xml
> +	<!--	<plugins>
En vez de comentarlo, mejor borrarlo, no?

2020-06-12 12:16 UTC, icossinib commented on model/src/main/db/templateDB.properties
>  tx_timestamp=0
Este archivo ya no hace falta, hay que borrarlo.

2020-06-12 12:16 UTC, icossinib commented on pom.xml
> +		<hsqldb.version>2.3.4</hsqldb.version>
estas tres variables, ya no se usan. son de la bbdd en memoria

2020-06-30 06:39 UTC, icossinib requested changes

2020-06-30 06:39 UTC, icossinib commented on model/src/main/db/templateDB.script
> +SET DATABASE UNIQUE NAME HSQLDB687727E49B
Carlos, estos archivos que están en la carpeta DB, ya no hacen falta al usar la BBDD del proyecto (la de postgresql)

2020-06-30 08:29 UTC, carlosgonzalez-campusdual commented on model/src/main/db/templateDB.script
> +SET DATABASE UNIQUE NAME HSQLDB687727E49B
ya están resueltos los cambios

2020-06-30 11:46 UTC, merged